CREATE TABLE IF NOT EXISTS agent_profiles (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL UNIQUE,
  agency_name VARCHAR(150) NOT NULL,
  license_number VARCHAR(50) NOT NULL UNIQUE,
  experience_years INT UNSIGNED NOT NULL,
  specialization VARCHAR(100) NULL,
  office_address VARCHAR(255) NULL,
  city VARCHAR(100) NULL,
  bio TEXT NULL,
  verification_status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_agent_profiles_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;