export const DEMO_PROPERTIES = [
  {
    id: 1,
    title: "Modern Luxury Villa in Bole",
    location: {
      address: "Bole",
      city: "Addis Ababa",
      state: "Addis Ababa",
      country: "Ethiopia",
      postalCode: "1000",
      latitude: 9.0192,
      longitude: 38.7525,
    },
    price: 5450000,
    status: "Active",
    listingType: "For Sale",
    propertyType: "Villa",
    categoryId: 2,
    bedrooms: 5,
    bathrooms: 6,
    parking: 2,
    area: 6500,
    areaUnit: "sq ft",
    description:
      "A modern luxury villa located in Bole featuring spacious living areas, premium finishes, a large kitchen, private garden, modern security systems, and comfortable bedrooms designed for family living.",
    amenities: [
      "Private Garden",
      "Smart Home",
      "Modern Kitchen",
      "Security System",
      "Garage",
      "Swimming Pool",
    ],
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1800&q=90",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=85",
    ],
    agent: {
      id: 1,
      name: "Abebe Bekele",
      role: "Senior Real Estate Agent",
      photo: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=500&q=85",
      experienceYears: 8,
      rating: 5,
      location: "Bole, Addis Ababa",
      phone: "+251911234567",
      email: "abebe.bekele@eliteproperties.et",
      bio: "Experienced real estate professional specializing in premium residential properties in Addis Ababa. Abebe helps clients find quality homes and investment opportunities.",
    },
  },

  {
    id: 2,
    title: "Elegant Family Home in CMC",
    location: {
      address: "CMC",
      city: "Addis Ababa",
      state: "Addis Ababa",
      country: "Ethiopia",
      postalCode: "1000",
      latitude: 9.0005,
      longitude: 38.8275,
    },
    price: 3200000,
    status: "Active",
    listingType: "For Sale",
    propertyType: "House",
    categoryId: 3,
    bedrooms: 4,
    bathrooms: 4,
    parking: 2,
    area: 4200,
    areaUnit: "sq ft",
    description:
      "Elegant family home in CMC with spacious bedrooms, comfortable living rooms, a modern kitchen, private compound, and excellent access to schools, shopping centers, and major roads.",
    amenities: [
      "Private Compound",
      "Modern Kitchen",
      "Garage",
      "Backup Generator",
      "Security System",
      "Storage Room",
    ],
    images: [
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1800&q=90",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=85",
    ],
    agent: {
      id: 2,
      name: "Hana Tesfaye",
      role: "Residential Property Specialist",
      photo: "https://images.unsplash.com/photo-1598550874175-4d0ef436c909?auto=format&fit=crop&w=500&q=85",
      experienceYears: 6,
      rating: 4.8,
      location: "CMC, Addis Ababa",
      phone: "+251922345678",
      email: "hana.tesfaye@eliteproperties.et",
      bio: "Hana specializes in family homes and residential properties across Addis Ababa, helping buyers find comfortable and well-located properties.",
    },
  },

  {
    id: 3,
    title: "Contemporary Apartment in Kazanchis",
    location: {
      address: "Kazanchis",
      city: "Addis Ababa",
      state: "Addis Ababa",
      country: "Ethiopia",
      postalCode: "1000",
      latitude: 9.0186,
      longitude: 38.7676,
    },
    price: 1800000,
    status: "Active",
    listingType: "For Sale",
    propertyType: "Apartment",
    categoryId: 1,
    bedrooms: 3,
    bathrooms: 3,
    parking: 1,
    area: 1850,
    areaUnit: "sq ft",
    description:
      "Contemporary apartment in the heart of Kazanchis offering modern interiors, spacious bedrooms, large windows, secure parking, and convenient access to business centers, restaurants, and hotels.",
    amenities: [
      "Elevator",
      "Secure Parking",
      "24/7 Security",
      "Modern Kitchen",
      "Balcony",
      "Backup Power",
    ],
    images: [
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1800&q=90",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?auto=format&fit=crop&w=1200&q=85",
    ],
    agent: {
      id: 3,
      name: "Dawit Alemu",
      role: "Commercial & Residential Agent",
      photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=85",
      experienceYears: 7,
      rating: 4.9,
      location: "Kazanchis, Addis Ababa",
      phone: "+251933456789",
      email: "dawit.alemu@eliteproperties.et",
      bio: "Dawit works with both residential and commercial clients, specializing in apartments and investment properties in central Addis Ababa.",
    },
  },

  {
    id: 4,
    title: "Spacious Family Villa in Old Airport",
    location: {
      address: "Old Airport",
      city: "Addis Ababa",
      state: "Addis Ababa",
      country: "Ethiopia",
      postalCode: "1000",
      latitude: 8.9968,
      longitude: 38.7812,
    },
    price: 7200000,
    status: "Active",
    listingType: "For Sale",
    propertyType: "Villa",
    categoryId: 2,
    bedrooms: 6,
    bathrooms: 7,
    parking: 4,
    area: 8200,
    areaUnit: "sq ft",
    description:
      "Spacious family villa in Old Airport featuring large indoor and outdoor spaces, multiple bedrooms, landscaped gardens, private parking, and premium finishes suitable for large families.",
    amenities: [
      "Large Garden",
      "Private Pool",
      "Guest House",
      "Garage",
      "Home Office",
      "Security System",
    ],
    images: [
      "https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=1800&q=90",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85",
    ],
    agent: {
      id: 4,
      name: "Meron Girma",
      role: "Luxury Property Consultant",
      photo: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=500&q=85",
      experienceYears: 10,
      rating: 5,
      location: "Old Airport, Addis Ababa",
      phone: "+251944567890",
      email: "meron.girma@eliteproperties.et",
      bio: "Meron specializes in luxury villas and premium residential properties, providing clients with professional guidance throughout the buying process.",
    },
  },

  {
    id: 5,
    title: "Modern Townhouse in Saris",
    location: {
      address: "Saris",
      city: "Addis Ababa",
      state: "Addis Ababa",
      country: "Ethiopia",
      postalCode: "1000",
      latitude: 8.9508,
      longitude: 38.7829,
    },
    price: 2650000,
    status: "Active",
    listingType: "For Sale",
    propertyType: "House",
    categoryId: 3,
    bedrooms: 4,
    bathrooms: 4,
    parking: 2,
    area: 3600,
    areaUnit: "sq ft",
    description:
      "Modern townhouse in Saris designed for comfortable family living with bright interiors, spacious bedrooms, private outdoor space, modern kitchen, and secure parking.",
    amenities: [
      "Private Yard",
      "Modern Kitchen",
      "Parking",
      "Security System",
      "Laundry Room",
      "Storage Room",
    ],
    images: [
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=1800&q=90",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=85",
    ],
    agent: {
      id: 5,
      name: "Samuel Tadesse",
      role: "Property Consultant",
      photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=500&q=85",
      experienceYears: 5,
      rating: 4.7,
      location: "Saris, Addis Ababa",
      phone: "+251955678901",
      email: "samuel.tadesse@eliteproperties.et",
      bio: "Samuel helps clients find quality homes and investment opportunities in Addis Ababa's growing neighborhoods.",
    },
  },

  {
    id: 6,
    title: "Premium Penthouse Apartment",
    location: {
      address: "Kazanchis",
      city: "Addis Ababa",
      state: "Addis Ababa",
      country: "Ethiopia",
      postalCode: "1000",
      latitude: 9.0191,
      longitude: 38.7688,
    },
    price: 6800000,
    status: "Featured",
    listingType: "For Sale",
    propertyType: "Apartment",
    categoryId: 1,
    bedrooms: 4,
    bathrooms: 5,
    parking: 2,
    area: 3100,
    areaUnit: "sq ft",
    description:
      "Luxury penthouse apartment with panoramic city views, spacious open-plan interiors, premium kitchen finishes, private terrace, and secure underground parking.",
    amenities: [
      "Private Terrace",
      "City View",
      "Elevator",
      "Gym",
      "24/7 Security",
      "Underground Parking",
    ],
    images: [
      "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1800&q=90",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=85",
    ],
    agent: {
      id: 6,
      name: "Liya Worku",
      role: "Luxury Property Advisor",
      photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=500&q=85",
      experienceYears: 9,
      rating: 4.9,
      location: "Kazanchis, Addis Ababa",
      phone: "+251966789012",
      email: "liya.worku@eliteproperties.et",
      bio: "Liya specializes in luxury properties and high-end residential investments in prime locations.",
    },
  },

  {
    id: 7,
    title: "Luxury Villa with Swimming Pool",
    location: {
      address: "Ayat",
      city: "Addis Ababa",
      state: "Addis Ababa",
      country: "Ethiopia",
      postalCode: "1000",
      latitude: 9.0015,
      longitude: 38.898,
    },
    price: 8500000,
    status: "Featured",
    listingType: "For Sale",
    propertyType: "Villa",
    categoryId: 2,
    bedrooms: 6,
    bathrooms: 7,
    parking: 4,
    area: 9200,
    areaUnit: "sq ft",
    description:
      "Exceptional luxury villa featuring a private swimming pool, landscaped garden, spacious living areas, multiple bedrooms, and elegant contemporary architecture.",
    amenities: [
      "Swimming Pool",
      "Private Garden",
      "Guest House",
      "Smart Home",
      "Garage",
      "Security System",
    ],
    images: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1800&q=90",
      "https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=85",
    ],
    agent: {
      id: 7,
      name: "Michael Gebre",
      role: "Luxury Real Estate Agent",
      photo: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=500&q=85",
      experienceYears: 11,
      rating: 5,
      location: "Ayat, Addis Ababa",
      phone: "+251977890123",
      email: "michael.gebre@eliteproperties.et",
      bio: "Michael specializes in luxury villas and high-end residential properties in Addis Ababa's premier neighborhoods.",
    },
  },

  {
    id: 8,
    title: "Affordable Family House in Gerji",
    location: {
      address: "Gerji",
      city: "Addis Ababa",
      state: "Addis Ababa",
      country: "Ethiopia",
      postalCode: "1000",
      latitude: 9.006,
      longitude: 38.854,
    },
    price: 2250000,
    status: "Active",
    listingType: "For Sale",
    propertyType: "House",
    categoryId: 3,
    bedrooms: 3,
    bathrooms: 3,
    parking: 2,
    area: 2800,
    areaUnit: "sq ft",
    description:
      "Comfortable family house in Gerji with three bedrooms, spacious living areas, private compound, parking, and convenient access to schools and shopping areas.",
    amenities: [
      "Private Compound",
      "Parking",
      "Modern Kitchen",
      "Storage",
      "Security System",
    ],
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1800&q=90",
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=85",
    ],
    agent: {
      id: 8,
      name: "Bethel Assefa",
      role: "Residential Agent",
      photo: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=500&q=85",
      experienceYears: 5,
      rating: 4.6,
      location: "Gerji, Addis Ababa",
      phone: "+251988901234",
      email: "bethel.assefa@eliteproperties.et",
      bio: "Bethel focuses on affordable residential properties for families and first-time homebuyers in Addis Ababa.",
    },
  },

  {
    id: 9,
    title: "Modern Apartment with City View",
    location: {
      address: "Meskel Square",
      city: "Addis Ababa",
      state: "Addis Ababa",
      country: "Ethiopia",
      postalCode: "1000",
      latitude: 9.0108,
      longitude: 38.761,
    },
    price: 2950000,
    status: "Active",
    listingType: "For Sale",
    propertyType: "Apartment",
    categoryId: 1,
    bedrooms: 3,
    bathrooms: 3,
    parking: 1,
    area: 2100,
    areaUnit: "sq ft",
    description:
      "Bright modern apartment featuring floor-to-ceiling windows, open-plan living space, contemporary kitchen, spacious bedrooms, and beautiful city views.",
    amenities: [
      "City View",
      "Elevator",
      "Balcony",
      "Modern Kitchen",
      "Parking",
      "24/7 Security",
    ],
    images: [
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1800&q=90",
      "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?auto=format&fit=crop&w=1200&q=85",
    ],
    agent: {
      id: 9,
      name: "Daniel Tesema",
      role: "Apartment Specialist",
      photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=85",
      experienceYears: 6,
      rating: 4.8,
      location: "Meskel Square, Addis Ababa",
      phone: "+251999012345",
      email: "daniel.tesema@eliteproperties.et",
      bio: "Daniel specializes in apartments and residential properties in central Addis Ababa's most desirable areas.",
    },
  },

  {
    id: 10,
    title: "Commercial Office Building in Bole",
    location: {
      address: "Bole Road",
      city: "Addis Ababa",
      state: "Addis Ababa",
      country: "Ethiopia",
      postalCode: "1000",
      latitude: 9.002,
      longitude: 38.787,
    },
    price: 14500000,
    status: "Featured",
    listingType: "For Sale",
    propertyType: "Commercial",
    categoryId: 4,
    bedrooms: 0,
    bathrooms: 6,
    parking: 12,
    area: 12500,
    areaUnit: "sq ft",
    description:
      "Premium commercial property located on Bole Road with multiple office floors, reception areas, parking spaces, meeting rooms, and excellent visibility.",
    amenities: [
      "Reception",
      "Conference Rooms",
      "Elevator",
      "Parking",
      "Backup Generator",
      "Security System",
    ],
    images: [
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1800&q=90",
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=85",
    ],
    agent: {
      id: 10,
      name: "Robel Girma",
      role: "Commercial Property Specialist",
      photo: "https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=500&q=85",
      experienceYears: 12,
      rating: 4.9,
      location: "Bole, Addis Ababa",
      phone: "+251900123456",
      email: "robel.girma@eliteproperties.et",
      bio: "Robel specializes in commercial real estate and investment properties, helping businesses find strategic locations.",
    },
  },

  {
    id: 11,
    title: "Luxury Residence in Old Airport",
    location: {
      address: "Old Airport",
      city: "Addis Ababa",
      state: "Addis Ababa",
      country: "Ethiopia",
      postalCode: "1000",
      latitude: 8.995,
      longitude: 38.779,
    },
    price: 9800000,
    status: "Featured",
    listingType: "For Sale",
    propertyType: "Villa",
    categoryId: 2,
    bedrooms: 7,
    bathrooms: 8,
    parking: 5,
    area: 10500,
    areaUnit: "sq ft",
    description:
      "High-end private residence with elegant architecture, large garden, swimming pool, spacious entertainment areas, guest accommodation, and premium finishes.",
    amenities: [
      "Swimming Pool",
      "Large Garden",
      "Guest House",
      "Home Theater",
      "Smart Home",
      "Garage",
    ],
    images: [
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1800&q=90",
      "https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=1200&q=85",
    ],
    agent: {
      id: 11,
      name: "Sara Mekonnen",
      role: "Luxury Property Consultant",
      photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=500&q=85",
      experienceYears: 13,
      rating: 5,
      location: "Old Airport, Addis Ababa",
      phone: "+251911234567",
      email: "sara.mekonnen@eliteproperties.et",
      bio: "Sara is a top luxury property consultant with expertise in high-end residential estates and premium real estate.",
    },
  },

  {
    id: 12,
    title: "Modern Family Villa in Yeka",
    location: {
      address: "Yeka",
      city: "Addis Ababa",
      state: "Addis Ababa",
      country: "Ethiopia",
      postalCode: "1000",
      latitude: 9.028,
      longitude: 38.842,
    },
    price: 4100000,
    status: "Active",
    listingType: "For Sale",
    propertyType: "Villa",
    categoryId: 2,
    bedrooms: 5,
    bathrooms: 5,
    parking: 3,
    area: 5800,
    areaUnit: "sq ft",
    description:
      "Beautiful contemporary family villa in Yeka with generous living areas, landscaped outdoor space, modern kitchen, private parking, and excellent neighborhood access.",
    amenities: [
      "Garden",
      "Modern Kitchen",
      "Garage",
      "Security System",
      "Laundry",
      "Storage",
    ],
    images: [
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1800&q=90",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=85",
    ],
    agent: {
      id: 12,
      name: "Henok Abebe",
      role: "Residential Property Agent",
      photo: "https://images.unsplash.com/photo-1504257432389-52343af06ae3?auto=format&fit=crop&w=500&q=85",
      experienceYears: 7,
      rating: 4.8,
      location: "Yeka, Addis Ababa",
      phone: "+251922345678",
      email: "henok.abebe@eliteproperties.et",
      bio: "Henok helps families find their dream homes in Addis Ababa's peaceful residential neighborhoods.",
    },
  },

  {
    id: 13,
    title: "Premium Apartment in Bole Atlas",
    location: {
      address: "Bole Atlas",
      city: "Addis Ababa",
      state: "Addis Ababa",
      country: "Ethiopia",
      postalCode: "1000",
      latitude: 9.006,
      longitude: 38.792,
    },
    price: 3600000,
    status: "Active",
    listingType: "For Sale",
    propertyType: "Apartment",
    categoryId: 1,
    bedrooms: 3,
    bathrooms: 3,
    parking: 2,
    area: 1950,
    areaUnit: "sq ft",
    description:
      "Premium apartment in Bole Atlas featuring modern interiors, spacious bedrooms, large windows, balcony, secure parking, and access to restaurants and shopping centers.",
    amenities: [
      "Balcony",
      "Elevator",
      "Parking",
      "Modern Kitchen",
      "Gym",
      "Security",
    ],
    images: [
      "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1800&q=90",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=85",
    ],
    agent: {
      id: 13,
      name: "Mimi Haile",
      role: "Apartment Consultant",
      photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=500&q=85",
      experienceYears: 6,
      rating: 4.7,
      location: "Bole Atlas, Addis Ababa",
      phone: "+251933456789",
      email: "mimi.haile@eliteproperties.et",
      bio: "Mimi specializes in apartment sales and residential property consulting in Addis Ababa.",
    },
  },

  {
    id: 14,
    title: "Lake View Villa in Bishoftu",
    location: {
      address: "Lake Bishoftu",
      city: "Bishoftu",
      state: "Oromia",
      country: "Ethiopia",
      postalCode: "1000",
      latitude: 8.752,
      longitude: 38.983,
    },
    price: 6200000,
    status: "Featured",
    listingType: "For Sale",
    propertyType: "Villa",
    categoryId: 2,
    bedrooms: 5,
    bathrooms: 5,
    parking: 3,
    area: 7600,
    areaUnit: "sq ft",
    description:
      "Beautiful lake-view villa in Bishoftu offering a peaceful environment, spacious garden, private swimming pool, modern interiors, and scenic outdoor living areas.",
    amenities: [
      "Lake View",
      "Swimming Pool",
      "Private Garden",
      "Outdoor Lounge",
      "Garage",
      "Security",
    ],
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1800&q=90",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=85",
    ],
    agent: {
      id: 14,
      name: "Yonatan Tadesse",
      role: "Luxury Property Agent",
      photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=500&q=85",
      experienceYears: 8,
      rating: 4.9,
      location: "Bishoftu, Oromia",
      phone: "+251944567890",
      email: "yonatan.tadesse@eliteproperties.et",
      bio: "Yonatan specializes in luxury properties and resort-style villas in beautiful locations outside Addis Ababa.",
    },
  },

  {
    id: 15,
    title: "Residential Land in Bole Arabsa",
    location: {
      address: "Bole Arabsa",
      city: "Addis Ababa",
      state: "Addis Ababa",
      country: "Ethiopia",
      postalCode: "1000",
      latitude: 8.98,
      longitude: 38.88,
    },
    price: 4500000,
    status: "Active",
    listingType: "For Sale",
    propertyType: "Land",
    categoryId: 5,
    bedrooms: 0,
    bathrooms: 0,
    parking: 0,
    area: 6000,
    areaUnit: "m²",
    description:
      "Residential land in a developing area of Bole Arabsa suitable for private residential development or investment.",
    amenities: [
      "Road Access",
      "Electricity Access",
      "Water Access",
      "Residential Zone",
    ],
    images: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1800&q=90",
      "https://images.unsplash.com/photo-1449157291145-7efd050a4d0e?auto=format&fit=crop&w=1200&q=85",
    ],
    agent: {
      id: 15,
      name: "Kalkidan Solomon",
      role: "Land & Investment Consultant",
      photo: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=500&q=85",
      experienceYears: 9,
      rating: 4.8,
      location: "Bole Arabsa, Addis Ababa",
      phone: "+251955678901",
      email: "kalkidan.solomon@eliteproperties.et",
      bio: "Kalkidan specializes in land sales and real estate investment opportunities, helping clients identify properties with strong development potential.",
    },
  },

  {
    id: 16,
    title: "Contemporary Villa in CMC",
    location: {
      address: "CMC Michael",
      city: "Addis Ababa",
      state: "Addis Ababa",
      country: "Ethiopia",
      postalCode: "1000",
      latitude: 9.006,
      longitude: 38.831,
    },
    price: 5750000,
    status: "Featured",
    listingType: "For Sale",
    propertyType: "Villa",
    categoryId: 2,
    bedrooms: 5,
    bathrooms: 6,
    parking: 3,
    area: 6900,
    areaUnit: "sq ft",
    description:
      "Contemporary villa in CMC with clean architectural lines, large windows, spacious rooms, landscaped compound, and premium modern finishes.",
    amenities: [
      "Private Garden",
      "Modern Kitchen",
      "Garage",
      "Large Windows",
      "Security System",
      "Storage",
    ],
    images: [
      "https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=1800&q=90",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=85",
    ],
    agent: {
      id: 16,
      name: "Rahel Girma",
      role: "Senior Property Advisor",
      photo: "https://images.unsplash.com/photo-1551836022-4c4c79ecde51?auto=format&fit=crop&w=500&q=85",
      experienceYears: 8,
      rating: 4.9,
      location: "CMC, Addis Ababa",
      phone: "+251966789012",
      email: "rahel.girma@eliteproperties.et",
      bio: "Rahel is a senior property advisor with expertise in premium residential properties and client satisfaction.",
    },
  },

  {
    id: 17,
    title: "Executive Office Space in Kazanchis",
    location: {
      address: "Kazanchis Business District",
      city: "Addis Ababa",
      state: "Addis Ababa",
      country: "Ethiopia",
      postalCode: "1000",
      latitude: 9.019,
      longitude: 38.769,
    },
    price: 7800000,
    status: "Active",
    listingType: "For Sale",
    propertyType: "Commercial",
    categoryId: 4,
    bedrooms: 0,
    bathrooms: 4,
    parking: 8,
    area: 6800,
    areaUnit: "sq ft",
    description:
      "Modern executive office space in Kazanchis designed for companies seeking a premium business address with meeting rooms, reception areas, and secure parking.",
    amenities: [
      "Reception",
      "Meeting Rooms",
      "Elevator",
      "Parking",
      "Backup Generator",
      "High-Speed Internet",
    ],
    images: [
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1800&q=90",
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=85",
    ],
    agent: {
      id: 17,
      name: "Fitsum Alemu",
      role: "Commercial Real Estate Advisor",
      photo: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=500&q=85",
      experienceYears: 10,
      rating: 4.9,
      location: "Kazanchis, Addis Ababa",
      phone: "+251977890123",
      email: "fitsum.alemu@eliteproperties.et",
      bio: "Fitsum specializes in commercial real estate and corporate property solutions for growing businesses.",
    },
  },

  {
    id: 18,
    title: "Modern Starter Home in Ayat",
    location: {
      address: "Ayat Zone 5",
      city: "Addis Ababa",
      state: "Addis Ababa",
      country: "Ethiopia",
      postalCode: "1000",
      latitude: 9.014,
      longitude: 38.897,
    },
    price: 2450000,
    status: "Active",
    listingType: "For Sale",
    propertyType: "House",
    categoryId: 3,
    bedrooms: 3,
    bathrooms: 3,
    parking: 2,
    area: 3200,
    areaUnit: "sq ft",
    description:
      "Well-designed starter home in Ayat with modern interiors, three bedrooms, private compound, parking, and convenient access to major roads and local services.",
    amenities: [
      "Private Compound",
      "Parking",
      "Modern Kitchen",
      "Storage",
      "Security",
    ],
    images: [
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1800&q=90",
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=1200&q=85",
    ],
    agent: {
      id: 18,
      name: "Meron Tadesse",
      role: "Residential Agent",
      photo: "https://images.unsplash.com/photo-1598550874175-4d0ef436c909?auto=format&fit=crop&w=500&q=85",
      experienceYears: 5,
      rating: 4.7,
      location: "Ayat, Addis Ababa",
      phone: "+251988901234",
      email: "meron.tadesse@eliteproperties.et",
      bio: "Meron focuses on residential properties and helping first-time homebuyers find their perfect starter homes.",
    },
  },
];
export const AGENTS = [
  {
    name: "Abebe Bekele",
    role: "Senior Agent",
    photo:
      "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=500&q=85",
  },
  {
    name: "Sara Tefera",
    role: "Luxury Specialist",
    photo:
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=500&q=85",
  },
  {
    name: "Dawit Haile",
    role: "Commercial Agent",
    photo:
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=500&q=85",
  },
  {
    name: "Selamawit Tadesse",
    role: "Residential Expert",
    photo:
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=500&q=85",
  },
  {
    name: "Yonas Mekonnen",
    role: "Property Advisor",
    photo:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=500&q=85",
  },
  {
    name: "Meron Girma",
    role: "Luxury Property Consultant",
    photo:
      "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=500&q=85",
  },
  {
    name: "Hana Tesfaye",
    role: "Residential Property Specialist",
    photo:
      "https://images.unsplash.com/photo-1598550874175-4d0ef436c909?auto=format&fit=crop&w=500&q=85",
  },
  {
    name: "Samuel Tadesse",
    role: "Property Consultant",
    photo:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=500&q=85",
  },
  {
    name: "Liya Alemu",
    role: "Real Estate Advisor",
    photo:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=500&q=85",
  },
  {
    name: "Michael Gebre",
    role: "Investment Specialist",
    photo:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=500&q=85",
  },
  {
    name: "Rahel Worku",
    role: "Residential Agent",
    photo:
      "https://images.unsplash.com/photo-1551836022-4c4c79ecde51?auto=format&fit=crop&w=500&q=85",
  },
  {
    name: "Nathan Assefa",
    role: "Commercial Property Advisor",
    photo:
      "https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=500&q=85",
  },
  {
    name: "Marta Yohannes",
    role: "Luxury Home Specialist",
    photo:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=500&q=85",
  },
  {
    name: "Henok Fikru",
    role: "Property Investment Advisor",
    photo:
      "https://images.unsplash.com/photo-1504257432389-52343af06ae3?auto=format&fit=crop&w=500&q=85",
  },
  {
    name: "Betty Solomon",
    role: "Real Estate Consultant",
    photo:
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=500&q=85",
  },
];

export const TESTIMONIALS = [
  
  {
    text: "The team was professional, patient, and very responsive whenever I had questions.",
    author: "Eden Alemu",
    role: "Homeowner",
  },
  {
    text: "I found a beautiful modern home in the exact neighborhood I wanted. The experience was excellent.",
    author: "Dawit Kebede",
    role: "Home Buyer",
  },
  {
    text: "Their market knowledge helped me make a much better investment decision.",
    author: "Saron Desta",
    role: "Property Investor",
  },
  {
    text: "The entire property search was organized and easy. I would happily use their service again.",
    author: "Thomas Bekele",
    role: "Homeowner",
  },
  {
    text: "From property recommendations to negotiation, the team provided excellent support at every step.",
    author: "Lidya Fikre",
    role: "Property Investor",
  },
];
export const NEARBY_PROPERTIES = [
 
  {
    id: 4,
    title: "Spacious Family Villa in Old Airport",
    location: {
      address: "Old Airport",
      city: "Addis Ababa",
      state: "Addis Ababa",
      country: "Ethiopia",
      postalCode: "1000",
      latitude: 8.9968,
      longitude: 38.7812,
    },
    price: 7200000,
    status: "Active",
    listingType: "For Sale",
    propertyType: "Villa",
    categoryId: 2,
    bedrooms: 6,
    bathrooms: 7,
    parking: 4,
    area: 8200,
    areaUnit: "sq ft",
    description:
      "Spacious family villa in Old Airport featuring large indoor and outdoor spaces, multiple bedrooms, landscaped gardens, private parking, and premium finishes suitable for large families.",
    amenities: [
      "Large Garden",
      "Private Pool",
      "Guest House",
      "Garage",
      "Home Office",
      "Security System",
    ],
    images: [
      "https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=1800&q=90",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85",
    ],
    agent: {
      id: 4,
      name: "Meron Girma",
      role: "Luxury Property Consultant",
      experienceYears: 10,
      rating: 5,
    },
  },

  {
    id: 5,
    title: "Modern Townhouse in Saris",
    location: {
      address: "Saris",
      city: "Addis Ababa",
      state: "Addis Ababa",
      country: "Ethiopia",
      postalCode: "1000",
      latitude: 8.9508,
      longitude: 38.7829,
    },
    price: 2650000,
    status: "Active",
    listingType: "For Sale",
    propertyType: "House",
    categoryId: 3,
    bedrooms: 4,
    bathrooms: 4,
    parking: 2,
    area: 3600,
    areaUnit: "sq ft",
    description:
      "Modern townhouse in Saris designed for comfortable family living with bright interiors, spacious bedrooms, private outdoor space, modern kitchen, and secure parking.",
    amenities: [
      "Private Yard",
      "Modern Kitchen",
      "Parking",
      "Security System",
      "Laundry Room",
      "Storage Room",
    ],
    images: [
      "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?auto=format&fit=crop&w=1800&q=90",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=85",
    ],
    agent: {
      id: 5,
      name: "Samuel Tadesse",
      role: "Property Consultant",
      experienceYears: 5,
      rating: 4.7,
    },
  },

  // =====================================================
  // 6
  // =====================================================

  {
    id: 6,
    title: "Premium Penthouse Apartment",
    location: {
      address: "Kazanchis",
      city: "Addis Ababa",
      state: "Addis Ababa",
      country: "Ethiopia",
      postalCode: "1000",
      latitude: 9.0191,
      longitude: 38.7688,
    },
    price: 6800000,
    status: "Featured",
    listingType: "For Sale",
    propertyType: "Apartment",
    categoryId: 1,
    bedrooms: 4,
    bathrooms: 5,
    parking: 2,
    area: 3100,
    areaUnit: "sq ft",
    description:
      "Luxury penthouse apartment with panoramic city views, spacious open-plan interiors, premium kitchen finishes, private terrace, and secure underground parking.",
    amenities: [
      "Private Terrace",
      "City View",
      "Elevator",
      "Gym",
      "24/7 Security",
      "Underground Parking",
    ],
    images: [
      "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1800&q=90",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=85",
    ],
    agent: {
      id: 6,
      name: "Liya Worku",
      role: "Luxury Property Advisor",
      experienceYears: 9,
      rating: 4.9,
    },
  },
];